# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88547772148501a04095cb41d729eb64c409924e3fef40f743a4745549702bb66e03ad65117e8c192c434c1cdb03d7ba25e3900f6570397aed31e93b449bf76

test:
  secret_key_base: 2b8fb0a6bd733e601b9e1a7a31cb73a8b00d0b029583712fae2db3b2578308752b520b449f1350b5096e8d477c2ec7b32961b09ca86f8ee42bc0377e531d9cfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
